### ISSUE TITLE
x11VNC

### ISSUE THREAD

**Issue by deanjwade** [nallar/DSLStatsDocker#1]
Hi Ross,

I have this running now in Docker on my NAS:
Model name: RS812+
CPU: INTEL Atom D2700
CPU clock rate: 2.13 GHz
CPU cores: 2
Total physical memory: 3072 MB
DSM version: DSM 6.0.2-8451 Update 9

It was crashing with default container low/normal privilege setting, I appear to have resolved this by raising the privilege setting to 'High'. See attached log.

The x11vnc you ideitified is not available to me: these are my options:

![x11vnc_options](https://cloud.githubusercontent.com/assets/25721439/22862302/fdc70c04-f123-11e6-97c8-26134c5a53ce.jpg)

What should I add?
[rossallan-dslstats1_20170212_1232.txt](https://github.com/nallar/DSLStatsDocker/files/769293/rossallan-dslstats1_20170212_1232.txt)

**Comment by LunNova** [comment]
From the logs it appears to be working. On the other hand my documentation isn't any good... You don't need to install any other dockers on the NAS for this to work. This docker includes the VNC server.

When you connect a VNC client (eg: [VNC viewer for Chrome](https://chrome.google.com/webstore/detail/vnc%C2%AE-viewer-for-google-ch/iabmpiboiopbgfabjmgeedhcmjenhbla?hl=en)) to the NAS on port 5900 the DSLStats GUI should show up.

 I'm not sure why it would require privileged mode... it doesn't for me.

Can you post the log when it tries to start when it's not privileged? I'd like to fix that as a container in privileged mode has access to all devices. It shouldn't need that.

**Comment by deanjwade** [comment]
OK, I have removed the other VNC package. I'm using the following client:
![clipboard01](https://cloud.githubusercontent.com/assets/25721439/22863084/1d96d646-f132-11e6-979e-4d342b727671.jpg)


My NAS is 192.168.9.71 so trying to connect with 192.168.9.71:5900 unsuccessfully (this is confirmed as working with my RPi) but just fails as following:
![container](https://cloud.githubusercontent.com/assets/25721439/22863126/a9256a6a-f132-11e6-9b1d-619aa7755c2f.jpg)

See log:
[rossallan-dslstats1.txt](https://github.com/nallar/DSLStatsDocker/files/769351/rossallan-dslstats1.txt)

**Comment by LunNova** [comment]
Try 192.168.9.71:32793

![image](https://cloud.githubusercontent.com/assets/782440/22863175/61b31d52-f133-11e6-87cd-77915a106800.png)

**Comment by deanjwade** [comment]
Why did I not think of trying that? - seeing it on the container overview it's obvious!

It worked, the VNC viewer then prompted me for the password. Two points that I think are both related to the high port in use instead of the 5900;

1. The password failed. I had previously entered the following in the terminal:
docker run -d \
--name=dslstats \
--net=bridge \
-p 5900:5900/tcp \
-e "VNC_PASSWORD"="123456789" \
-v /mnt/cache/appdata/dslstats:/config \
-v /etc/localtime:/etc/localtime:ro \
rossallan/dslstats

2. The high port increments each time I run the container, my last try was at 32798. So I assume all the other are still left allocated in the VNC server or IP stack.

Why is the high port range initially being created from?

**Comment by deanjwade** [comment]
I must have been wrong about privileges required - it seem to be running fine - i'm not sure what has changed.

Any idea what the default X11vnc password would be? I would like to get past the password prompt

**Comment by LunNova** [comment]
The default is "CHANGEME". To set it to something with the NAS UI you'll need to find an option to set environment vars (must exist?), then set VNC_PASSWORD to whatever you want.

**Comment by LunNova** [comment]
The port allocation is completely outside of my control - docker requires you to specify a port in the command. If you specifiy a given port, it will use that port. Any issue with it changing the port every time is due to the NAS software. Unfortunately I haven't used that so I can't give advice on how to stop it happening :(

**Comment by deanjwade** [comment]
nearly there:
![rui1](https://cloud.githubusercontent.com/assets/25721439/22866066/b7504bfc-f167-11e6-9c79-f5f5ef13b16d.jpg)

![rui2](https://cloud.githubusercontent.com/assets/25721439/22866067/b9f8f7be-f167-11e6-9c56-9af65af84dc5.jpg)

**Comment by deanjwade** [comment]
Any idea what these errors are caused by?
![error](https://cloud.githubusercontent.com/assets/25721439/22866084/158837ca-f168-11e6-8827-4a19fa09a80a.jpg)

**Comment by LunNova** [comment]
The mount for /etc/localtime is incorrect. It isn't strictly needed, it's used to ensure the timezone inside the container matches the timezone outside it.

It's possible that your NAS's UI already handles that, either in the same way or by setting the TZ environment variable for you. Try removing that mount option.

**Comment by deanjwade** [comment]
I figured how to specify the port and ignored -v settings.

It now runs, one problem;
the password is at the default of CHANGEME despite what I set. I've implemented as per the manual and faq for another container but no joy. Is there anything you can influence here?... Is this problem related how the X11VNC server has been integrated?

It would be good if you could resolve so that the VNC password can be changed.

**Comment by LunNova** [comment]
The password issue was due to a bug and my fault. It's fixed now in commit 0ff8d519a260b880885.

Try updating the container and setting the password should work.

**Comment by deanjwade** [comment]
Many thanks.

Here are detailed installation instructions for Synology +NAS machines.
[DSLStats_via_Docker_for_Synology_NAS.pdf](https://github.com/nallar/DSLStatsDocker/files/771953/DSLStats_via_Docker_for_Synology_NAS.pdf)

**Comment by LunNova** [comment]
Almost perfect, but that will leave you without a /config volume set up. It still works like this, but it means the config is stored inside the container instead of somewhere else, so if the container is updated you will need to reconfigure DSLStats.

**Comment by deanjwade** [comment]
Done:
![qqq](https://cloud.githubusercontent.com/assets/25721439/22948804/c2d4159e-f2f7-11e6-9662-fc1e261b0a75.jpg)

I note that the webserver on port 55555 is not configured?

**Comment by LunNova** [comment]
There are some issues with DSLStats' built in web server. http://forum.kitz.co.uk/index.php?topic=19296.0

As a workaround I have made it start another web server in commit 997e53690d1668d39

To enable it with the new container version, add the port 8080, then enable the web server in DSLStats. Leave the port in DSLStats at the default, that setting doesn't actually matter.

**Comment by deanjwade** [comment]
I'm very interested in the details and need to grasp how this works.

I do have a webserver already running on my NAS so that would probably be more elegant, and I could include setup info in the instructions.

**Comment by deanjwade** [comment]
I have an application to monitor LTE and found this re' data.
[http://sh.com.hr/en/modificiranje-huawei-e3372-lte-sticka/](url)

I assume it would be easy to mod the DSLStats source? what do you think?

**Comment by deanjwade** [comment]
This web server is still not working for me. Any idea why?
![ra](https://cloud.githubusercontent.com/assets/25721439/22974609/0fb4bdcc-f37b-11e6-953d-6ad97ed8d6d4.jpg)
see attached log
[rossallan-dslstats.txt](https://github.com/nallar/DSLStatsDocker/files/777014/rossallan-dslstats.txt)

**Comment by LunNova** [comment]
It's still running an older version of the container which doesn't have the webserver workaround.

Looks like updating a container using the synology UI is a bit of an involved process: https://forum.synology.com/enu/viewtopic.php?t=107508#p446211

**Comment by deanjwade** [comment]
it's easy for me to start afresh.

would you be able to publish the container with the work around for me to add, launch and test please?

**Comment by LunNova** [comment]
The updated version is already pushed.

If you want to make it place the webserver files in a different location, you could add a volume with the container path being: /root/.dslstats/webserver/ and the real path being wherever you want it to put the webserver files.

**Comment by deanjwade** [comment]
Thanks. all up and running but images etc. are not displayed.
This is my webserver:

![aaaaaa](https://cloud.githubusercontent.com/assets/25721439/22978960/94ecd4dc-f38c-11e6-84c4-b6a3df17c177.jpg)

So what should the -v be?

**Comment by LunNova** [comment]
`-v /web/dslstats:/root/.dslstats/webserver/`, assuming web/web_images is in the root directory. If not /whateverthepathis/web/dslstats.

**Comment by deanjwade** [comment]
The NAS web servers default index.html is in /web so it this correct:
![qqqq](https://cloud.githubusercontent.com/assets/25721439/22980193/ba1e5ad8-f390-11e6-9ab0-1a0b59c46955.jpg)

or have I got the two expressions switched?

Given that the NAS web server is using index.html what is the DSLStats home page?

**Comment by LunNova** [comment]
The bottom one for the config mount is correct.
The top one is wrong.

Left should read:

    /web/dslstats

Right should read:

    /root/.dslstats/webserver

(note the . before dslstats)

There is no index page. Visit /dslstats/ and pick one of the HTML files view a certain stat, for example connspeed.html.

**Comment by deanjwade** [comment]
It running but /web/dslstats is not being populated with files from the webserver.

Or should the webserver be looking in /root/.dslstats/webserver ?

**Comment by LunNova** [comment]
`/web/dslstats` is where it should be putting them.

Not sure why it's not working. Double check the paths and that the web server is enabled in DSLstats?

**Comment by deanjwade** [comment]
All working except that the `connectionstats.txt` info required by `combined.html` at the bottom is missing due to this file not being generated.

Any idea why the file `connectionstats.txt` is not being generated by DSLStats?... or is this one for Eric?

**Comment by LunNova** [comment]
Nope, no clue. Probably a DSLstats issue and not related to the docker.

**Comment by deanjwade** [comment]
Just waiting for Eric to fix and publish corrected version.

**Comment by deanjwade** [comment]
It seems that Its been fixed;
http://dslstats.me.uk/changelog.html

Could you do the honours and let me know when ready please?

**Comment by LunNova** [comment]
Updated to 5.9: ed39a5b8cc78ed3
