### ISSUE TITLE
Synology timezone

### ISSUE THREAD

**Issue by andyfitter** [nallar/DSLStatsDocker#2]
My Synology box is running with timezone set to GMT+0. (London) There seems to be no way of setting it to be a Daylight saving zone as we have in the UK, however the actual time set on the Synology box is correct.

MyDSLWebStats is complaining that my time is 1 hour out and to restart the DSLStats program.

I've done this multiple times (Restarted the docker container, rebooted the synology etc) but to no effect. 

Any suggestions on how this can be fixed? Can the Docker container be forced to run in the 'correct' BST zone?

**Comment by LunNova** [comment]
Sorry about the late reply - didn't notice this one.

As discussed on http://forum.kitz.co.uk/index.php/topic,19340.0.html you've already resolved this :)
