### ISSUE TITLE
Is the latest Automated build on Docker broken?

### ISSUE THREAD

**Issue by andyfitter** [nallar/DSLStatsDocker#3]
Appears to be errors in gzip in the build logs  https://hub.docker.com/r/rossallan/dslstats/builds/bgffbfe5tgmwdhwekqmjsmf/

**Comment by andyfitter** [comment]
Looks like a new build kicked off again at 17:45 or so and this one seems to be OK

**Comment by LunNova** [comment]
That was me, after seeing this issue. f3b3f3fd62df892e

It should now fail the build if something goes wrong.

**Comment by andyfitter** [comment]
Cheers, all looks good again after the last build.

Was really coincidental timing, as it was only about two hours earlier I installed watchtower, which automatically pulled the new version down. Before that I’d happily been using the original version for some while.

Andy.
